version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - .:/app
    command: bash -lc "python manage.py migrate --noinput || true; python manage.py runserver 0.0.0.0:8000"
